project:
  type: website
  output-dir: docs
  resources:
    - "showcase/*.pdf"

website:
  title: "Making a language"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: content.qmd
        text: Content
      - href: assessment.qmd
        text: Assessment
      - href: showcase.qmd
        text: Showcase

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    include-in-header: assets/head.html
    include-after-body: assets/after-body.html

editor: visual

callout-icon: false
