project:
  type: website
  output-dir: docs

website:
  title: "Making a language"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.html
        text: Syllabus
      - href: assessment.html
        text: Assessment

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

callout-icon: false
