---
title: "GR Seminar — Making a language"
---

Welcome to the site of the Guided Research seminar *Making a language: the art and science of conlanging*.

Here you can find the course overview. For more details check the [Course content](content.qmd) and the [Assessment](assessment.qmd) page.

## Course description

In this seminar, you will learn about and practice with **conlanging**, the process of **creating a constructed language, or conlang**.

The seminar is built around the task of crafting a conlang from the ground up while researching about common and rare linguistic patterns as found in the languages of the world, grammar writing and historical reconstruction. Through step-by-step guidance, you will learn how to develop your conlang.

You will be able to choose your assessment task from the following: a grammar sketch, which will also include a short written passage in your conlang accompanied by interlinear glossing; or the description of a constructed history of your conlang or conlang families; or an in-depth analysis of a specific phenomenon in your conlang.

## Reading list

The reading list for this seminar can be found [here](https://eu01.alma.exlibrisgroup.com/leganto/public/44UOE_INST/lists/38657069480002466?auth=SAML).
