---
title: "Syllabus"
editor: visual
---

Here you can find a more detailed syllabus of the course.

Please note that I expect you to come to every class **prepared**, which mean:

1.  You have read that week's **readings** and
2.  You have completed that week's **homework tasks** and/or thought about the week's **questions**, as detailed below.

**Formative assessments** are due at noon on the day of the seminar. These are designed for you to receive feedback on parts of your conlang's reference grammar (which will be built in into your second summative assessment). Note that formative assessments are based on the topic of the previous week.

More information on **formative and summative assessments** can be found on the [Assessment](assessment.html) page.

The [**reading list**]{.underline} for this seminar can be found [here](https://eu01.alma.exlibrisgroup.com/leganto/public/44UOE_INST/lists/38657069480002466?auth=SAML).

## Week 1

There is no class in Week 1.

## Week 2: Conlanging and the languages of the world

::: {.callout-tip collapse="false"}
## Readings

-   [Conlanging 101](https://conlang.org/26c3.pdf) by Sai Emrys, Alex Fink and David Peterson.
    -   An introduction to *conlanging*, the art of constructing artificial languages.
-   The Language Construction Kit (LCK), Ch *The overall process*.
    -   The LCK is the go-to book to teach yourself how to build a *conlang* from scratch. The Chapter *The overall process* gives you an overview of the entire conlanging process.

The following are readings that you can skim through in Week 1 and read at your own time throughout the course.

-   Croft, Bill. 2003. *Typology and universals*. Ch 1.
    -   Classical book on linguistic typology (and typological linguistics). The first chapter introduces you to typological linguistics. Pay special attention to the *Problem of cross-linguistic variability*.
-   Aikhenvald, Alexandra. 2014. *The art of grammar: A practical guide*. Ch 1.
    -   Writing a reference grammar is an art and a science in itself. This textbook covers the main practical aspects of how to go about writing a grammar. Chapter 1 focusses on what a reference grammar is and its structure and offers guidance on linguistic analysis and argumentation.
:::

::: {.callout-warning collapse="false"}
## Homework

-   Pick a language you are curious about and find a descriptive grammar of that language in the library.
    -   You can choose any language, except "big" languages like English, Spanish, Mandarin, Japanese, Arabic, French, German, ... (what's the fun in that!).

    -   Remember to bring the descriptive grammar to class.
:::

## Week 3: Sound systems

::: {.callout-important collapse="true"}
## Formative 1: Language context

Submit **one or two paragraphs of language context** for your conlang. Remember to give a name to your conlang (you can change this later).

-   A *language context article* can include "information about speaker demography, social organisation, culture, linguistic ecology, language vitality, and language use and transmission in the local community, its diaspora and the Internet, discussion of the range of languages/varieties in use by speakers, including socio-cultural factors affecting language/variety choice".
-   A more detailed description of language context articles can be found here: <http://www.elpublishing.org/about-language-contexts>. Remember that you are supposed to **write only one or two paragraphs**.
-   To find inspiration, check the language context papers at <http://www.elpublishing.org/language-contexts>.
:::

::: {.callout-tip collapse="true"}
## Readings

-   How to Create a Language, Ch [Sounds](https://www.angelfire.com/scifi2/nyh/how__all.html).
-   Gordon, Matthew. 2016. *Phonological typology*. Ch 3.
:::

::: {.callout-warning collapse="true"}
## Homework

-   Find the phonemic inventories of two languages that are related to the "adopted language" you picked in Week 2.
-   Check out phonemic inventory tendencies on the [Universals Archive](https://typo.uni-konstanz.de/rara/category/universals-archive/).
:::

## Week 4: The lexicon

::: {.callout-important collapse="true"}
## Formative 2: Phonemic inventory

Submit the phonemic inventory of your conlang.

-   This should include at least a table of consonants and a table of vowels, plus a description of the major allophones of the consonantal and vocalic phonemes.
-   You can also include information on phonemic vowel/consonant sequences (if they exist in your conlang).
-   Feel free to expand on any aspect of the sound system of your conlang.
:::

::: {.callout-tip collapse="true"}
## Readings

-   LCK, Ch *Word building*.
-   Haspelmath, Martin. 2010. *Understanding morphology*. Ch 2.
:::

::: {.callout-warning collapse="true"}
## Homework

-   Which word classes are there in your adopted language?
:::

## Week 5: Events, actions and verbs

::: {.callout-important collapse="true" icon="false"}
## Formative 3: Swadesh list

Submit a **Swadesh list of your conlang with a paragraph describing the main features of the lexicon**.

-   Please, use [this template](https://docs.google.com/spreadsheets/d/15X0cIHE9OiCwQnGeGLulGuh2QkVXJIZgQ0Mf4VZBRNA/edit?usp=sharing).

-   It is up to you how many words you wish to submit, but you should include at least 25 words and words from at least 5 categories.

-   At a minimum you should include the phonemic transcription and the part of speech of your chosen words.

-   If you already have a writing system/transliteration/transcription system in mind, you can also include that.
:::

::: {.callout-tip collapse="true" icon="false"}
## Readings

-   Aikhenvald, Alexandra. 2014. *The art of grammar: A practical guide*. Ch 7.

-   Croft, William. 2022. *Morphosyntax: Constructions of the world's languages*. Ch 2.
:::

::: {.callout-warning collapse="true" icon="false"}
## Homework

-   What characteristics of verbs in the adopted language you picked caught your attention and why?
:::

## Week 6: Objects and nouns

::: {.callout-important collapse="true" icon="false"}
## Formative 4: Morphosyntax of verbs (action predication)

Submit one/two pages that explain the morphosyntax of your conlang's verbal system.

-   Make sure to include at least one full verbal paradigm.
-   Provide a description of how different verbal features (person, gender, number, tense, aspect, mood, evidentiality, ...?) are coded in your conlang (affixes, particles, ...?) and provide a few examples for each.
:::

::: {.callout-tip collapse="true" icon="false"}
## Readings

-   Haspelmath, Martin. 2010. *Understanding morphology*. Ch 5.
:::

::: {.callout-warning collapse="true" icon="false"}
## Homework

-   What characteristics of nouns in the adopted language you picked caught your attention and why?
:::

## Week 7: Basic clauses

::: {.callout-tip collapse="true" icon="false"}
## Readings

-   Croft, Bill. 2003. *Typology and universals*. Ch 5.5.
-   Cristofaro, Sonia. 2012. *Cognitive explanations, distributional evidence, and diachrony: Theory and data in cognitive linguistics*. Sec 1-2.
:::

::: {.callout-warning collapse="true" icon="false"}
## Homework

-   Which syntactic aspect of the adopted language you picked caught your attention and why?
:::

## Week 8: Modification and subordination

::: {.callout-important collapse="true" icon="false"}
## Summative 1

Please, check the [Assesment](assessment.html) page.
:::

::: {.callout-tip collapse="true" icon="false"}
## Readings

-   Croft, William. 2022. *Morphosyntax: Constructions of the world's languages*. Ch 4.
:::

## Week 9: Reference grammars

::: {.callout-important collapse="true" icon="false"}
## Formative 5: Nouns and basic clauses

Submit three/five pages that explain the morphosyntax of nouns and basic clauses in your conlang.

-   Include a description of nominal morphology, if any (gender, number, case, ...?), and illustrate with examples.

-   Discuss the structure of basic clauses (transitive, intransitive, ditransitive, ...). Make sure to discuss the morphosyntactic alignment of your conlang.
:::

::: {.callout-warning collapse="true" icon="false"}
## Homework

-   Choose a glossed example from your adopted grammar.
:::

## Week 10: Writing systems

::: {.callout-important collapse="true" icon="false"}
## Formative 6: Interlinear gloss

Submit a short text in your conlang with full interlinear glossing.

-   In Week 9, you will learn how to produce publication quality interlinear glosses using LaTeX and the expex package.

-   You will produce the interlinear gloss of your text with those tools and submit the gloss as PDF.
:::

::: {.callout-warning collapse="true" icon="false"}
## Homework

-   Transcribe your name in a non-Roman-based writing system.
-   If your name is already in a non-Roman-based writing system, pick a different one.
:::

## Week 13

::: {.callout-important collapse="true" icon="false"}
## Summative 2

Please, check the [Assesment](assessment.html) page.
:::
